name: gis

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12

  - folium=0.18.0
  - geojson=3.1.0
  - geopandas=0.14.4
  - geopy=2.4.1
  - jupyterlab=4.2.5
  - matplotlib=3.8.4
  - osmnx=1.9.4
